version: "3"
services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"

  server:
    container_name: docker-node-c
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - postgres
    image: node
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  postgres:
    container_name: docker-postgres-c
    image: postgres
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

